package main.jdbc.ex.pgms;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class AutoGeneratedKeysEx {

  public static void main(String[] args) {

    Connection con = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    try {
      Class.forName("oracle.jdbc.driver.OracleDriver");
      con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:ORCL", "dev_user", "devuser");
      String query = "insert into employee_details(employee_name, salary, dept_id, joining_date) values(?, ?, ?, ?)";
      pstmt = con.prepareStatement(query, PreparedStatement.RETURN_GENERATED_KEYS);
      // pstmt.setInt(1, 1);
      pstmt.setString(1, "Vasugi");
      pstmt.setString(2, "90000");
      pstmt.setInt(3, 4);
      pstmt.setDate(4, Date.valueOf("2019-03-01"));
      pstmt.executeUpdate();
      rs = pstmt.getGeneratedKeys();
      if (rs != null && rs.next()) {
        System.out.println("Generated Emp Id: " + rs.getInt(1));
      }

    } catch (ClassNotFoundException | SQLException ex) {
      // TODO Auto-generated catch block
      ex.printStackTrace();
    } finally {
      try {
        if (rs != null)
          rs.close();
        if (pstmt != null)
          pstmt.close();
        if (con != null)
          con.close();
      } catch (Exception ex1) {
      }
    }
  }
}
